apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "ls-app.fullname" . }}
  labels:
    {{- include "ls-app.labels" . | nindent 4 }}
spec:
  gateways:
    - {{ .Values.ezua.virtualService.istioGateway }}
  hosts:
    - {{ .Values.ezua.virtualService.endpoint | required "\nValid .Values.virtualService.endpoint is required !" }}
  http:
    - match:
        - uri:
            prefix: /
      rewrite:
        uri: /
      route:
        - destination:
            host: {{ include "ls-app.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ index .Values "app"  "service" "port" }}